metabolism
BotfatherDev/CommonChatModer pull request #24
Opened 2020-11-28 07:16 UTC by KeyCreator

Добавлена команда расчета суточной нормы калорий для человека metabolism. Сбор данных сделан через машину состояний. Чтобы хотелось улучшить, но пока не хватает знаний:

1. Автоматически финишировать машину состояний по завершению заданного времени, если пользователь перестал заполнять данные (бросил это делать)

1. Перевести проверку введенных численных данных на корректность в middleware

1. Совместить текстовое поле ввода данных и инлайн-кнопку "Отмена", чтобы пользователь мог прервать процесс.

2020-11-29 14:40 UTC, Latand requested changes
В целом неплохо, но надо исправить код по замечаниям

2020-11-29 14:40 UTC, Latand commented on .env.dist
> -# Telegram API Token
Почему этот файл был удален? Надо вернуть

2020-11-29 14:40 UTC, Latand commented on handlers/essential/metabolism.py
> +@dp.message_handler(content_types=ContentType.TEXT, state=Metabolism.weight)
`content_types=ContentType.TEXT`

Зачем? оно и так по умолчанию стоит

2020-11-29 14:40 UTC, Latand commented on handlers/essential/metabolism.py
> +    await call.answer(cache_time=60)
Не надо пихать это всюду. Если ты внизу убираешь клавиатуру - это действие бесполезно

2020-11-29 14:40 UTC, Latand commented on handlers/essential/metabolism.py
> +    await call.answer(cache_time=60)
я про call.answer

2020-11-29 14:40 UTC, Latand commented on keyboards/inline/metabolism.py
> +# metabolism_activity_markup = InlineKeyboardMarkup(inline_keyboard=[
Закомментированный блок можно вообще убрать

2020-12-02 10:03 UTC, KeyCreator commented on .env.dist
> -# Telegram API Token
Вернул

2020-12-02 10:03 UTC, KeyCreator commented on handlers/essential/metabolism.py
> +@dp.message_handler(content_types=ContentType.TEXT, state=Metabolism.weight)
Принято, убрал

2020-12-02 10:04 UTC, KeyCreator commented on handlers/essential/metabolism.py
> +    await call.answer(cache_time=60)
Принято. Убрал call.answer в функциях, где я убираю клавиатуру

2020-12-02 10:04 UTC, KeyCreator commented on keyboards/inline/metabolism.py
> +# metabolism_activity_markup = InlineKeyboardMarkup(inline_keyboard=[
Убрал

2020-12-02 10:18 UTC, KeyCreator commented
Исправления внес. Прошу проверить

2020-12-02 11:06 UTC, Latand approved these changes
Отлично!

2020-12-02 11:06 UTC, Latand approved these changes

2020-12-02 11:08 UTC, merged