Рефакторинг
BotfatherDev/CommonChatModer pull request #5
Opened 2020-05-13 08:23 UTC by comictomcat

2020-05-13 19:04 UTC, Latand requested changes

2020-05-13 19:04 UTC, Latand commented on handlers/basic/basic.py
> +    if types.ChatType.is_private(message):
Лучше сделать два разных хендлера на разные типы чатов используя фильтр. Не мешай все в одном хендлере

2020-05-13 19:04 UTC, Latand commented on handlers/basic/basic.py
> +        keyboard_markup = types.InlineKeyboardMarkup(row_width=3)
Клавиатуры надо создавать в папке с клавиатурами

2020-05-13 19:04 UTC, Latand commented on handlers/basic/basic.py
> +        row_btns = (types.InlineKeyboardButton(text, callback_data=data) for text, data in text_and_data)
немного неочевидно что сюда попадают за кнопки, лучше сделать список списков как я делал, или отдельно объекты для разных кнопок с соответствующими им названиям

2020-05-13 19:04 UTC, Latand commented on handlers/basic/basic.py
> +        await help(message)
в отдельный хендлер

2020-05-13 19:04 UTC, Latand commented on handlers/basic/basic.py
> +        await help(message)
Можешь просто на следующий хендлер сверху добавить декоратор с фильтром

2020-05-13 19:04 UTC, Latand commented on handlers/basic/basic.py
> +        await help(message)
Который внизу

2020-05-13 19:04 UTC, Latand commented on handlers/basic/basic.py
> +    if types.ChatType.is_private(message):
Отдельный хендлер

2020-05-13 19:04 UTC, Latand commented on handlers/basic/basic.py
> +    await message.reply("".join(text))
Вместо \n в каждой строке лучше сделай тут `"\n".join()`

2020-05-13 19:04 UTC, Latand commented on handlers/basic/errors.py
> +from loguru import logger
Смысл менять его на логуру?

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
>  @dp.message_handler(IsGroup(), AdminFilter(), Command(commands=["ro"], prefixes="!/"))
Вот есть фильтр на группу, его и используй

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +    command_parse = re.compile(r"(!ro|/ro) ?(\d+)? ?(\w+)?")
неправильная регулярка, она не будет парсить больше одного слова

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +        member_mentioned = message.reply_to_message.from_user.get_mention(as_html=True)
не обязательно все это иметь под `try:`
выведи все что не нужно ниже

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +            f"Пользователю @{member_id} запрещено писать сообщения до {until_date} админом @{admin_id}"
зачем логгить с айдишниками? тем более ставить перед ними собачку.

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +        service_message = await message.reply("Сообщение самоуничтожится через 5 секунд", reply=False)
почему реплай убрал? Надо понимать какое именно сообщение самоуничтожится

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +            reply=False
почему реплай убрал? Надо понимать какое именно сообщение самоуничтожится

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +        service_message = await message.answer(f"Сообщение самоуничтожится через 5 секунд.", reply=False)
В  message.answer по умолчанию нет реплая

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +        logger.info(f"Бот не смог замутить пользователя @{member_id}")
собачка и айдишник?

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +        member_mentioned = message.reply_to_message.from_user.get_mention(as_html=True)
Убери все ниже из `try:`

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> -        can_add_web_page_previews=True,
Это все нужно оставить

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +        can_send_messages=True
ты тут ему только текст разрешишь отправлять, а остальное запретишь

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +    service_message = await message.reply("Сообщение самоуничтожится через 5 секунд.", reply=False)
реплай тру

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +        f"Пользователь @{member_id} был размучен администратором @{admin_id}"
нужен юзернейм (если нет его, то тогда фулл нейм)

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +        member_mentioned = message.reply_to_message.from_user.get_mention(as_html=True)
.

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +        service_message = await message.answer("Сообщение самоуничтожится через 5 секунд.", reply=False)
реплай тру

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +            reply=False
опять же, тру

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +        service_message = await message.answer(f"Сообщение самоуничтожится через 5 секунд.", reply=False)
тру

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +        logger.info(f"Бот не смог забанить пользователя @{member_id}")
не айди

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +        member_mentioned = message.reply_to_message.from_user.get_mention(as_html=True)
.

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +    await message.answer(f"Пользователь {member_mentioned} был разбанен", reply=False)
.

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +    service_message = await message.reply("Сообщение самоуничтожится через 5 секунд.", reply=False)
.

2020-05-13 19:04 UTC, Latand commented on handlers/groups/moderate_chat.py
> +        f"Пользователь @{member_id} был забанен админом @{admin_id}"
.

2020-05-13 19:04 UTC, Latand commented on handlers/groups/service_messages.py
> +    # Удаляем сообщение через 5 минут
зачем удалять?

2020-05-13 19:04 UTC, Latand commented on handlers/groups/service_messages.py
> +    elif message.from_user.id == 1143077900:
Не бери тут айдишник, т.к. он может быть у другого бота другим. Сделай `bot.id`

2020-05-18 10:53 UTC, 0Kit commented on filters/private_chat.py
> +        return message.chat.type in types.ChatType.PRIVATE
return message.chat.type == types.ChatType.PRIVATE

2020-05-18 10:53 UTC, 0Kit commented on handlers/basic/basic.py
> +    """Хендлер на команду !/help
Хендлер на команду help
Зачем тут префиксы указывать?

2020-05-18 10:53 UTC, 0Kit commented on handlers/basic/basic.py
> +    """Хендлер на команду !/start
Всё те же префиксы, или указывай их ниже в докстринге

2020-05-18 10:53 UTC, 0Kit commented on handlers/basic/basic.py
>          )
<b>Основные комманды</b>
Мы ставили html, а тут я пока разобрался чо происходит, чуть не здох. Или F-strings юзай, чтобы код читабельнее был

2020-05-18 11:01 UTC, Latand commented on handlers/basic/basic.py
>          )
А мне нравится))

2020-05-18 11:01 UTC, Latand commented on handlers/basic/basic.py
>          )
Правда я бы сделал это через 
```
"""
Текст
"""
```

2020-05-18 11:02 UTC, Latand commented on handlers/basic/basic.py
>          )
А еще можно сделать списком строк и связать их через `"\n".join()`

2020-05-18 11:02 UTC, Latand commented on handlers/basic/basic.py
> +    """Хендлер на команду !/start
мне кажется для старта и хелпа префиксы не нужны. Там достаточно /start /help

2020-05-18 11:03 UTC, Latand commented on filters/private_chat.py
> +        return message.chat.type in types.ChatType.PRIVATE
+

2020-05-18 13:26 UTC, Latand approved these changes

2020-05-18 13:26 UTC, merged